### ISSUE TITLE
Install instructions (in README) for Package Manager are not correct?

### ISSUE THREAD

**Issue by noio** [modio/modio-unity#64]
The repository `https://github.com/modio/modio-unity-upm.git` does not exist? Or is it private?

**Comment by intenscia** [comment]
It's private, @modio-jackson can assist with access to it!

**Comment by modio-jackson** [comment]
Hi @noio, thanks for pointing this out.
Unfortunately the UPM option is currently unavailable as the project wasn't initially constructed with this in mind and I've had to deprecate it for the time being. I've removed it from the README to avoid further confusion.
We will have a UPM installation option again towards the end of Q1 2021 for the next major version, but for now I recommend using the latest release.
