### ISSUE TITLE
UnityWebRequest.isNetworkError is obsolete

### ISSUE THREAD

**Issue by Laumania** [modio/modio-unity#83]
I installed 2.3.4 from Github and it seems to work fine, however, it's a little annoying to get a ton of warnings similar to this.

`Assets\Plugins\mod.io\Runtime\RequestManagement\ImageRequestManager.cs(502,42): warning CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'`

**Comment by modio-jackson** [comment]
Thanks - I haven't been testing in Unity 2020, but I'll make sure run it through the cycle and ensure that I clean these warnings up for the next release.

**Comment by modio-jackson** [comment]
Fixed for v2.3.5
