### ISSUE TITLE
Unable to build addressable content

### ISSUE THREAD

**Issue by Laumania** [modio/modio-unity#84]
It looks like it actually builds, but Addressable complains about the naming.

Tested with Addressable Version 1.18.9 - June 08, 2021

`Address '_EditorImages [mod.io]' cannot contain '[ ]'.
UnityEditor.GenericMenu:CatchMenu (object,string[],int)`

![image](https://user-images.githubusercontent.com/1378458/137995338-d187061d-f626-4c94-9d78-e839617b36b3.png)

**Comment by modio-jackson** [comment]
Fixed for v2.3.5
